/* Auto-generated by run_benchmark.py — DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "btf_action_functions_generated.h"
#include "btreefy/btreefy.h"
#include "btreefy/btreefy_objs.h"

extern struct btf_node nodes[];
extern size_t          nodes_size;

int count = 0;

/* ── Action implementations (70% SUCCESS / 30% FAILURE) ── */

enum btf_node_status A(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status B(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_SUCCESS_STATUS;
}

enum btf_node_status C(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status D(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status E(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status F(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_SUCCESS_STATUS;
}

enum btf_node_status G(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status H(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_SUCCESS_STATUS;
}

enum btf_node_status I(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status J(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_SUCCESS_STATUS;
}

enum btf_node_status K(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status L(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status M(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status N(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_SUCCESS_STATUS;
}

enum btf_node_status O(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_FAILURE_STATUS;
}

enum btf_node_status P(struct btf_tree *tree)
{
    // printf("Count = %d\n", count++);
    return BTF_SUCCESS_STATUS;
}

/* ── Comparison for qsort (descending — slowest first) ── */
static int cmp_desc(const void *a, const void *b)
{
    long long da = *(const long long *) a;
    long long db = *(const long long *) b;
    return (db > da) - (db < da);
}

int main(void)
{
    srand(42);

    struct btf_tree tree;
    btf_init(&tree, nodes, (uint32_t) nodes_size);

    long long times[20];

    for (int t = 0; t < 20; t++)
    {
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        btf_tick_tree(&tree);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        times[t] = (long long) (t1.tv_sec - t0.tv_sec) * 1000000000LL
                   + (t1.tv_nsec - t0.tv_nsec);
    }

    /* Sort descending to isolate the 5 slowest */
    qsort(times, 20, sizeof(long long), cmp_desc);

    long long sum = 0;
    for (int i = 0; i < 5; i++)
    {
        sum += times[i];
    }
    /* Print average of the 5 slowest ticks in nanoseconds */
    printf("%lld\n", sum / 5);

    return 0;
}
