CONFIG_GPIO=y
CONFIG_EVENTS=y
# First config to get POSIX thread running w/o statically allocated stack
CONFIG_POSIX_API=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_POOL_SIZE=6
CONFIG_MAX_PTHREAD_MUTEX_COUNT=6

# BTreeFy Runner Selection
# CONFIG_BTREEFY_RUNNER_ZEPHYR=y
# Default is POSIX if not set
