/* Auto-generated by run_benchmark.py — DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "btreefy/btreefy.h"
#include "btreefy/btreefy_objs.h"
#include "btf_action_functions_generated.h"

extern struct btf_node nodes[];
extern size_t          nodes_size;

/* ── Action implementations (70% SUCCESS / 30% FAILURE) ── */
enum btf_node_status action_A(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_B(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_C(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_D(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_E(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_F(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_G(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_H(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_I(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_J(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_K(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_L(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_M(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}

enum btf_node_status action_N(struct btf_tree *tree) {
    return (rand() % 10 < 7) ? BTF_SUCCESS_STATUS : BTF_FAILURE_STATUS;
}


/* ── Comparison for qsort (descending — slowest first) ── */
static int cmp_desc(const void *a, const void *b) {
    long long da = *(const long long *)a;
    long long db = *(const long long *)b;
    return (db > da) - (db < da);
}

int main(void) {
    srand(42);

    struct btf_tree tree;
    btf_init(&tree, nodes, (uint32_t)nodes_size);

    long long times[20];

    for (int t = 0; t < 20; t++) {
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        btf_tick_tree(&tree);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        times[t] = (long long)(t1.tv_sec - t0.tv_sec) * 1000000000LL
                 + (t1.tv_nsec - t0.tv_nsec);
    }

    /* Sort descending to isolate the 5 slowest */
    qsort(times, 20, sizeof(long long), cmp_desc);

    long long sum = 0;
    for (int i = 0; i < 5; i++) {
        sum += times[i];
    }
    /* Print average of the 5 slowest ticks in nanoseconds */
    printf("%lld\n", sum / 5);

    return 0;
}
