// ─────────────────────────────────────────────────────────────────────────────
// report_p2_scaling.typ — Phase 2 Report: Scaling Analysis / Exponential Wall
// BT MinLA Project · UFAL PPGI · 2026
// ─────────────────────────────────────────────────────────────────────────────
#import "preamble.typ": *
#show: report-setup

// ── Title block ───────────────────────────────────────────────────────────────
#align(center)[
  #text(fill: muted, size: 10pt)[BT MinLA Project · UFAL PPGI · 2026]
  #v(8pt)
  #text(fill: clr_text, size: 22pt, weight: "bold")[
    Phase 2 Report: The Exponential Wall\
    Empirical Scaling Analysis of the MILP Solver
  ]
  #v(6pt)
  #grid(columns: (1fr, 1fr, 1fr),
    align(center)[#pill("n ∈ {5,8,10,12,15,20}")],
    align(center)[#pill("5 instances / n", color: accent2)],
    align(center)[#pill("5-min timeout", color: warn)],
  )
  #v(4pt)
  #text(fill: muted, size: 10pt)[Victor Oliveira · victor.rsoliveira\@gmail.com]
]

#v(16pt)
#divider
#v(16pt)

// ─────────────────────────────────────────────────────────────────────────────
= Motivation
// ─────────────────────────────────────────────────────────────────────────────

Phase 1 established the MILP formulation and demonstrated optimality on the
5-node toy example. The formulation is exact, but its complexity profile is
problematic: the unique-slot constraints introduce $O(n^2)$ binary variables
$z_(i j)$, and the branch-and-bound search space grows *exponentially* with $n$.

Real BTreeFy applications typically deploy trees in the range $n = 20$–$200$
nodes. If the MILP solver cannot terminate within a practical time limit for
those sizes, an alternative approach — a heuristic — is needed. Phase 2 makes
this claim *empirical and reproducible* by measuring solver wall-clock time
across a range of $n$ values, documenting the exact point where CBC transitions
from tractable to intractable. This is the scientific motivation for Phase 3.

// ─────────────────────────────────────────────────────────────────────────────
= Experimental Design
// ─────────────────────────────────────────────────────────────────────────────

== Instance Generation

Random BT instances are generated by `random_bt.py` using a top-down
construction:

#algo(title: "Random BT construction (random_bt.py)")[
  #set text(size: 10pt)
  #bullet[Start with a single root node (control node).]
  #bullet[Maintain a pool of *expandable* control nodes.]
  #bullet[At each step: pick a node from the pool; attach 2–4 children to it.]
  #bullet[New children join the pool only while unplaced nodes remain.]
  #bullet[Remaining budget assigned to root if pool empties prematurely.]
  #bullet[Reindex all nodes in DFS pre-order (matching the real parser output).]
  #bullet[Derive LCRS fields (parent/child/sibling) from the resulting tree.]
]

This ensures every generated graph is structurally valid: control nodes have
at least 2 children, leaves have no children, and all LCRS invariants hold.

== Protocol

#card(title: "Experiment parameters", color: accent)[
  #set text(size: 10pt)
  #grid(columns: (1fr, 1fr), gutter: 14pt,
    [
      - *n values:* {5, 8, 10, 12, 15, 20}
      - *Instances per n:* 5 (seeds 0–4)
      - *Total runs:* 30
    ],
    [
      - *Time limit:* 300 s (5 min) per instance
      - *Solver:* PuLP 2.x / CBC backend
      - *Hardware:* local workstation (single thread)
    ]
  )
]

Per run, the following metrics are recorded:

- `solve_time` — wall-clock seconds until CBC returns (or times out)
- `milp_cost` — best MinLA objective value found
- `status` — `Optimal` / `Feasible` (timed out with incumbent) / `Timeout`
- `binary_vars` — $n(n-1)$, the count of $z_(i j)$ binary variables

== Complexity Analysis

The binary variable count $n(n-1)$ is the driver of intractability:

#card(title: "Binary variable count vs. n", color: warn)[
  #set text(size: 10pt)
  #grid(columns: (auto, auto, auto, auto, auto, auto), gutter: 8pt,
    [*n*], [5], [8], [10], [12], [15],
    [*z vars*], [20], [56], [90], [132], [210],
    [*n*], [20], [25], [30], [50], [100],
    [*z vars*], [380], [600], [870], [2450], [9900],
  )
  The $O(n^2)$ growth means that doubling $n$ roughly *quadruples* the number
  of binary variables. CBC's branch-and-bound explores an exponential number of
  nodes in this binary space.
]

// ─────────────────────────────────────────────────────────────────────────────
= Results
// ─────────────────────────────────────────────────────────────────────────────

== Solver Time vs. n

#figure(
  image("figures/scaling_wall.png", width: 100%),
  caption: [
    Mean and maximum CBC solve time vs. number of BT nodes $n$.
    Log-scale y-axis. Shaded region marks instances that hit the 5-minute
    timeout. Each point aggregates 5 random BT instances.
  ]
)

== Observations

#result-box[
  The plot confirms the exponential wall predicted by the $O(n^2)$ binary
  variable analysis:

  - For $n <= 10$: CBC terminates *optimally* in under 60 seconds on all instances.
  - For $n = 12$: solve times span 83 s–300 s; one instance (seed=4) hit the exact timeout boundary.
  - For $n >= 15$: *every* instance saturated the 5-minute wall-clock limit.
  - For $n = 20$: all 5 instances timed out at exactly ~300 s.

  *The empirical failure point is $n approx 12$–$15$*, consistent with the
  $O(n^2)$ binary count analysis.
  #ref-cite("Petit, 2011 — MinLA scaling characterisation")
]

#note-box[
  *Note on CBC status at timeout:* For $n >= 15$, the solver reported status
  `"Optimal"` despite saturating the time limit. This is a known PuLP/CBC
  behaviour: when the branch-and-bound tree is exhausted *or* the incumbent
  matches the LP relaxation bound at the moment of timeout, CBC marks the
  solution optimal. The ~300 s wall times confirm these were timeout-bounded
  runs, not fast proofs. For the Optimality Gap analysis in Phase 4, only
  instances with `solve_time < 250 s` are treated as verified-optimal ground
  truth (i.e., $n <= 12$ only).
]

== Summary Table

#card(title: "Scaling results — measured data", color: border)[
  #set text(size: 10pt, font: "Fira Code")
  ```
  n   bin_vars  avg_time(s)  min_time   max_time   verified?
   5        20         0.45      0.20s      0.92s   YES (all Optimal)
   8        56         3.50      1.64s      7.11s   YES (all Optimal)
  10        90        39.71     23.38s     56.38s   YES (all Optimal)
  12       132       173.60     82.97s    300.45s   YES (4/5 clear)
  15       210       300.35    300.27s    300.43s   NO  (timeout-bounded)
  20       380       300.23    300.19s    300.31s   NO  (timeout-bounded)
  ```
  #v(4pt)
  #set text(size: 9pt, font: "Libertinus Serif")
  Note: n=12 seed=4 hit the timeout boundary and is treated as unverified for Phase 4.
]

// ─────────────────────────────────────────────────────────────────────────────
= Discussion
// ─────────────────────────────────────────────────────────────────────────────

== Why Does CBC Fail Here?

Branch-and-bound on Mixed-Integer Programs has worst-case complexity
exponential in the number of binary variables. The $n(n-1)$ ordering
variables $z_(i j)$ create a search space of $2^{n(n-1)}$ candidate
combinations. Even with LP relaxations, cutting planes, and heuristic
branching, CBC cannot prune enough of this space to terminate within 5 minutes
once $n >= 15$.

Notably, the formulation is correct and complete — given infinite time, CBC
would find the global optimum for any $n$. The wall is purely computational,
not mathematical. This is precisely the NP-Hardness of MinLA manifesting
in practice. #ref-cite("Garey & Johnson, 1979")

== Why Not Tighten the MILP?

Several standard techniques can push the intractability boundary further (to
$n approx 20$–$25$): valid inequalities (e.g. symmetry-breaking constraints),
problem-specific cuts, or warm-starting CBC from a good heuristic solution.
These are deliberate scope-out decisions: the research objective is to
*characterise* the wall, not to maximise the reach of the exact solver.
The heuristic in Phase 3 must work well for $n = 20$–$200$, a range where
MILP is never competitive regardless of formulation tightening.

// ─────────────────────────────────────────────────────────────────────────────
= Conclusion
// ─────────────────────────────────────────────────────────────────────────────

Phase 2 delivers two scientific contributions:

#card(title: "Scientific outputs", color: accent2)[
  #set text(size: 10pt)
  #bullet[*Empirical Exponential Wall:* Reproducible evidence that CBC becomes intractable at $n approx 15$ for BT-structured MinLA instances. This is a BT-specific data point in the MinLA benchmark literature.]
  #bullet[*Motivation for the heuristic:* The data formally justifies Phase 3's Simulated Annealing approach — not as an engineering convenience, but as a *necessity* for real-world BT sizes.]
  #bullet[*Ground-truth boundary:* Instances with $n <= 12$ can be solved exactly; these form the validation set for the Phase 4 Optimality Gap analysis.]
]

// ─────────────────────────────────────────────────────────────────────────────
= References
// ─────────────────────────────────────────────────────────────────────────────

#divider
#v(6pt)
#set text(size: 10pt)

- *Garey, M.R. & Johnson, D.S. (1979).* Computers and Intractability: A Guide to the Theory of NP-Completeness. Freeman. — MinLA NP-Hardness; exponential wall theoretical grounding.

- *Petit, J. (2011).* Experiments on the minimum linear arrangement problem. _Journal of Experimental Algorithmics_, 8. — Empirical scaling characterisation of MinLA solvers; benchmark methodology.

- *Pettis, K. & Hansen, R.C. (1990).* Profile guided code positioning. _ACM SIGPLAN Notices_, 25(6), 16–27. — Motivates Phase 3 Fiedler vector initialization.
