
if(ZEPHYR_BASE)
    zephyr_library_named(BTreeFy-Src)
    zephyr_library_sources(btreefy.c btreefy_policies.c btf_blackboard.c)

    if(CONFIG_BTREEFY_RUNNER STREQUAL "ZEPHYR")
        zephyr_library_sources(runners/btf_tree_runner_zephyr.c)
    elseif(CONFIG_BTREEFY_RUNNER STREQUAL "POSIX")
        zephyr_library_sources(runners/btf_tree_runner_posix.c)
    else()
        message(WARNING "Unknown BTreeFy runner: ${CONFIG_BTREEFY_RUNNER}. Defaulting to POSIX.")
        zephyr_library_sources(runners/btf_tree_runner_posix.c)
    endif()

    zephyr_library_link_libraries(zephyr_interface)
else()
    add_library(BTreeFy-Src STATIC btreefy.c btreefy_policies.c btf_blackboard.c)
    if(BTREEFY_RUNNER STREQUAL "POSIX")
        target_sources(BTreeFy-Src PRIVATE runners/btf_tree_runner_posix.c)
    elseif(BTREEFY_RUNNER STREQUAL "BAREMETAL")
        target_sources(BTreeFy-Src PRIVATE runners/btf_tree_runner_baremetal.c)
    elseif(BTREEFY_RUNNER STREQUAL "ZEPHYR")
        message(FATAL_ERROR "Zephyr runner is not supported in non-Zephyr builds")
    endif()
endif()

target_include_directories(BTreeFy-Src PUBLIC "${PROJECT_SOURCE_DIR}/include")